type TaskStatus = 'pending' | 'in_progress' | 'done';

type PriorityLabel = 'low' | 'medium' | 'high';

interface Task {
  id: string;
  description: string; // max 200 chars
  impact: number; // 1-10
  confidence: number; // 1-10
  ease: number; // 1-10
  status: TaskStatus;
  explanation: string; // generated by AI or handwritten
}

// Response from Gemini service
interface GeminiAnalysis {
  impact: number;
  confidence: number;
  ease: number;
  explanation: string;
}

interface TaskValidationErrors {
  description?: string;
  impact?: string;
  confidence?: string;
  ease?: string;
}

interface TaskValidationResult {
  isValid: boolean;
  errors: TaskValidationErrors;
}

export type {
  TaskStatus,
  GeminiAnalysis,
  PriorityLabel,
  TaskValidationErrors,
  TaskValidationResult,
};
export type { Task };